name: Release

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          BASE=$(jq -r '.AppVersion' source/LivelyInfo.json | cut -d. -f1-3)
          TAG="v$BASE.${{ github.run_number }}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "zipname=matrix-wallpaper-$TAG.zip" >> $GITHUB_OUTPUT

      - name: Create zip
        run: cd source && zip -r "../${{ steps.version.outputs.zipname }}" .

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.tag }}
          files: ${{ steps.version.outputs.zipname }}
